stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/awdpay/event-frontend

build:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com
  script:
    # ⚠️ correction du chemin dockerfile (minuscule)
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -f docker/dockerfile .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - prod

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/deploy_key
    - chmod 600 ~/.ssh/deploy_key
    - ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts
  script:
    - |
      ssh -i ~/.ssh/deploy_key $VPS_USER@$VPS_HOST << 'EOF'

        echo "Login registry"
        echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com

        echo "Pull image"
        docker pull registry.gitlab.com/awdpay/event-frontend:latest

        echo "Stop old container"
        docker stop event_frontend || true
        docker rm event_frontend || true

        echo "Run new container"
        docker run -d --name event_frontend -p 3000:80 registry.gitlab.com/awdpay/event-frontend:latest

        echo "Frontend déployé avec succès"
      EOF
  only:
    - prod