server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Frontend React (fichiers statiques)
    location / {
        try_files $uri /index.html;
    }

    # Gestion SPA (React Router)
    error_page 404 /index.html;
}