server {
    listen 80;
    server_name awardsdan.com www.awardsdan.com;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
    }

    error_page 404 /index.html;
}